// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieCollection.Models;

public partial class Category
{
    public int Id { get; set; }

    [Display(Name = "Category")]
    public string CatName { get; set; }

    public virtual ICollection<Movie> Movies { get; set; } = new List<Movie>();
}