// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MovieCollection.Models;

public partial class Movie
{
    public int Id { get; set; }

    [Display(Name = "Title")]
    [Required(ErrorMessage = "Please enter a title")]
    public string Title { get; set; }

    public double Rating { get; set; }

    [Display(Name = "Image")]
    //[Required(ErrorMessage = "Please select an image")]
    public string Image { get; set; }

    
    [Display(Name = "Image")]
    [NotMapped]
    public IFormFile ImageFile { get; set; }

    [Display(Name = "Release Date")]
    [Required(ErrorMessage = "Please enter a release date")]
    [DataType(DataType.Date)]
    //[DisplayFormat(DataFormatString = "{0:yyyy}", ApplyFormatInEditMode = true)]
    public DateOnly ReleaseDate { get; set; }

    [Display(Name = "View Date")]
    [DataType(DataType.Date)]
    //[DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
    public DateOnly? ViewDate { get; set; }

    [Display(Name = "CategoryId")]
    public int CategId { get; set; }

    [Display(Name = "PlatformId")]
    public int PlatformId { get; set; }
    
    [Display(Name = "Category")]
    [Required(ErrorMessage = "Please select a category")]
    public virtual Category Categ { get; set; }

    public virtual ICollection<MoviesActor> MoviesActors { get; set; } = new List<MoviesActor>();

    [Display(Name = "Available On")]
    [Required(ErrorMessage = "Please select a platform")]
    public virtual Platform Platform { get; set; }
}